const supabaseUrl='https://rbphgvnwmzjeuvyrasvy.supabase.co';
const supabaseAnonKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJicGhndm53bXpqZXV2eXJhc3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MjM3MjksImV4cCI6MjA4OTk5OTcyOX0.ug7k4jDtYwudivBJaWyKuCdwbt3GVnLXtWtpsBUhvEQ";
const token=new URLSearchParams(location.hash.slice(1)).get('token');
const send=document.getElementById('sendBtn'),status=document.getElementById('status');send.disabled=true;
const api=async body=>{const r=await fetch(supabaseUrl+'/functions/v1/booking-public',{method:'POST',headers:{apikey:supabaseAnonKey,Authorization:'Bearer '+supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({...body,token})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Kunne ikke hente booking.');return result;};
async function load(){try{if(!/^[a-f0-9]{64}$/.test(token||''))throw new Error('Denne lenken mangler sikker tilgang. Kontakt Skallstuggu for en ny privat bookinglenke.');const {booking,messages}=await api({action:'get'});const info=document.getElementById('bookingInfo');info.replaceChildren();for(const text of [booking.name,booking.start_date+' → '+booking.end_date,'Status: '+(booking.cancelled_at?'Avbestilt':booking.status==='approved'?'Godkjent':booking.status==='rejected'?'Avslått':'Under behandling'),booking.booking_total_ore!=null?'Total inkl. mva: '+(booking.booking_total_ore/100).toLocaleString('nb-NO')+' kr':'',booking.message]){if(text){const p=document.createElement('p');p.textContent=text;info.append(p);}}
const container=document.getElementById('messages');container.replaceChildren();for(const m of messages){const box=document.createElement('div');box.className='message '+(m.sender==='admin'?'admin':'customer');const meta=document.createElement('div');meta.className='meta';meta.textContent=(m.sender==='admin'?'Skallstuggu':'Deg')+' · '+new Date(m.created_at).toLocaleString('nb-NO');const text=document.createElement('div');text.textContent=m.message;box.append(meta,text);container.append(box);}if(!messages.length)container.textContent='Ingen meldinger ennå.';send.disabled=false;
}catch(error){document.getElementById('messages').textContent=error.message;send.disabled=true;}}
send.addEventListener('click',async()=>{send.disabled=true;try{await api({action:'message',message:document.getElementById('replyMessage').value.trim()});document.getElementById('replyMessage').value='';status.textContent='Svaret er sendt.';await load();}catch(error){status.textContent=error.message;send.disabled=false;}});
load();
